version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: ${LOCAL_USER:-devuser}
        USER_UID: ${LOCAL_UID:-1000}
        USER_GID: ${LOCAL_GID:-1000}
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/${LOCAL_USER:-devuser}/.ssh
      - ~/.gitconfig:/home/${LOCAL_USER:-devuser}/.gitconfig
    command: sleep infinity
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - GEM_HOME=/usr/local/bundle
      - HOME=/home/${LOCAL_USER:-devuser}
      - LOCAL_USER=$LOCAL_USER
